### ISSUE TITLE
Is there an expectation that there will be something in the database on first use ?

### ISSUE THREAD

**Issue by shearichard** [zoltan-nz/meetup-contacts-app-2021#6]
I'm only making this an issue because it's an easier way to document it than using Discord. After pulling the most recent commit ( 4a78b1fdfc5eba1eb60477a2d2f5716e23918b21 ) I 

- created a new Firebase project and a new app within it 
- updated the contents of .env.local
- 'yarn start'

The home page is served without problem but when I select 'Chat' I get this ...

![image](https://user-images.githubusercontent.com/403435/124063396-df31fc80-da86-11eb-9e96-24e22ac87d6e.png)

... It occurred to me that perhaps I was the first person to try using this with a completely empty database as last Thursday we fiddled around a fair bit and possibly entered some data before trying to read it ? 

I did think about entering some data throught the Firebase console which would match this model (from `pages/chat/ChatIndexPage.tsx`) ...

```
interface Message {
  id: string;
  text: string;
}
```

... but I remembered there were a few idiosyncrasies with the way FB structured the data we came across last Thursday and I thought it might be easier if @zoltan-nz could maybe provide a sample of what he's got in his database ? And if anyone else could provide their experiences of running this that would be useful too.

Thanks

**Comment by zoltan-nz** [comment]
Thanks for reporting this bug. It is already fixed. Cheers. :)
